version: "3.9"

services:
  db:
    image: postgres:13.6
    env_file: .env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=boilerplate-db
    ports:
      - "5432:5432"
